"""Create requests table

Revision ID: 113f3096a37a
Revises: b943a11ae26d
Create Date: 2021-03-22 16:13:17.082610

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '113f3096a37a'
down_revision = 'b943a11ae26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'requests',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('caregiver', sa.Text(), nullable=True),
        sa.Column('patient', sa.Text(), nullable=True),
        sa.Column('Creation Date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(('caregiver',), ['users.User ID'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(('patient',), ['users.User ID'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_Creation Date'), 'requests', ['Creation Date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_Creation Date'), table_name='requests')
    op.drop_table('requests')
    # ### end Alembic commands ###
