"""Create OTP table

Revision ID: 43effb4cd46d
Revises: 7ee9744924a4
Create Date: 2021-03-22 00:12:17.397643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = '43effb4cd46d'
down_revision = '7ee9744924a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'otps',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('code', sa.String(length=500), nullable=False),
        sa.Column('user', sa.String(length=20), nullable=True),
        sa.Column('is_validated', sa.Boolean(), nullable=True, server_default='0'),
        sa.Column('purpose', sa.Text, nullable=True, server_default='registration'),
        sa.Column('generation_date', sa.DateTime(), nullable=False, server_default=func.now()),
        sa.ForeignKeyConstraint(('user',), ['users.Phone Number'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otps')
    # ### end Alembic commands ###
