"""Map patients and caregivers

Revision ID: 65dde4a56323
Revises: 94c84a89210e
Create Date: 2021-03-31 06:52:04.621998

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '65dde4a56323'
down_revision = '94c84a89210e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'patient_caregivers',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('caregiver', sa.Text(), nullable=True),
        sa.Column('patient', sa.Text(), nullable=True),
        sa.Column('tag', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(('caregiver',), ['users.User ID'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(('patient',), ['users.User ID'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_caregivers')
    # ### end Alembic commands ###
