"""create user logins table

Revision ID: 8bbb4bdadb96
Revises: 43effb4cd46d
Create Date: 2021-03-22 01:36:58.849045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = '8bbb4bdadb96'
down_revision = '43effb4cd46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_logins',
        sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('User', sa.Text(), nullable=False),
        sa.Column('Device ID', sa.Text(), nullable=False),
        sa.Column('logged_in', sa.Boolean(), nullable=True),
        sa.Column('Login Date', sa.DateTime(), nullable=True, server_default=func.now()),
        sa.ForeignKeyConstraint(('User',), ['users.User ID'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('ID'),
        sa.UniqueConstraint('User', 'Device ID')
    )
    op.create_index(op.f('ix_user_logins_Login Date'), 'user_logins', ['Login Date'], unique=False)
    op.create_index(op.f('ix_user_logins_logged_in'), 'user_logins', ['logged_in'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_logins_logged_in'), table_name='user_logins')
    op.drop_index(op.f('ix_user_logins_Login Date'), table_name='user_logins')
    op.drop_table('user_logins')
    # ### end Alembic commands ###
