"""Update database 1

Revision ID: 94c84a89210e
Revises: 113f3096a37a
Create Date: 2021-03-31 06:44:52.460380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c84a89210e'
down_revision = '113f3096a37a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_relatives', sa.Column('tag', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('Email Address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'Email Address')
    op.drop_column('patient_relatives', 'tag')
    # ### end Alembic commands ###
