"""Create alerts table

Revision ID: b943a11ae26d
Revises: 36ee8081de34
Create Date: 2021-03-22 16:01:23.233257

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b943a11ae26d'
down_revision = '36ee8081de34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'alerts',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('patient', sa.Text(), nullable=True),
        sa.Column('Creation Date', sa.DateTime(), nullable=True),
        sa.Column('Creator', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(('patient',), ['users.User ID'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_Creation Date'), 'alerts', ['Creation Date'], unique=False)
    op.create_index(op.f('ix_alerts_Creator'), 'alerts', ['Creator'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_Creator'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_Creation Date'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
