"""create system database

Revision ID: c1ae154be95f
Revises: 
Create Date: 2021-03-20 22:30:30.292282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = 'c1ae154be95f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'roles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('Name', sa.String(length=60), nullable=False),
        sa.Column('Description', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_Name'), 'roles', ['Name'], unique=True)
    op.create_table(
        'scheduled_tasks',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=True),
        sa.Column('start', sa.DateTime(), nullable=False),
        sa.Column('interval', sa.Integer(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('cancelled', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_tasks_name'), 'scheduled_tasks', ['name'], unique=False)
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('Identification Number', sa.Text(), nullable=True),
        sa.Column('Full Name', sa.Text(), nullable=True),
        sa.Column('Phone Number', sa.String(length=20), nullable=False),
        sa.Column('User ID', sa.Text(), nullable=False),
        sa.Column('Gender', sa.Text(), nullable=True, server_default='Unspecified'),
        sa.Column('Residence', sa.String(length=300), nullable=True),
        sa.Column('Password', sa.String(length=255), nullable=False, server_default=''),
        sa.Column('Profile Picture', sa.String(length=500), nullable=True),
        sa.Column('ID Picture', sa.String(length=500), nullable=False),
        sa.Column('Active', sa.Boolean(), nullable=True, default='1'),
        sa.Column('Suspended', sa.Boolean(), nullable=True, default='0'),
        sa.Column('is_confirmed', sa.Boolean(), nullable=True, default='0'),
        sa.Column('Creation Date', sa.DateTime(), nullable=True, server_default=func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('Profile Picture')
    )
    op.create_index(op.f('ix_users_Identification Number'), 'users', ['Identification Number'], unique=False)
    op.create_index(op.f('ix_users_Creation Date'), 'users', ['Creation Date'], unique=False)
    op.create_index(op.f('ix_users_Active'), 'users', ['Active'], unique=False)
    op.create_index(op.f('ix_users_Suspended'), 'users', ['Suspended'], unique=False)
    op.create_index(op.f('ix_users_is_confirmed'), 'users', ['is_confirmed'], unique=False)
    op.create_index(op.f('ix_users_Full Name'), 'users', ['Full Name'], unique=False)
    op.create_index(op.f('ix_users_Phone Number'), 'users', ['Phone Number'], unique=True)
    op.create_index(op.f('ix_users_Residence'), 'users', ['Residence'], unique=False)
    op.create_index(op.f('ix_users_User ID'), 'users', ['User ID'], unique=True)
    op.create_index(op.f('ix_users_Gender'), 'users', ['Gender'], unique=False)
    op.create_table(
        'chats',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('Chat ID', sa.Integer(), nullable=False),
        sa.Column('relative', sa.Text(), nullable=True),
        sa.Column('patient', sa.Text(), nullable=True),
        sa.Column('disabled', sa.Boolean(), nullable=True),
        sa.Column('Creation Date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(('patient',), ['users.User ID'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(('relative',), ['users.User ID'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_Chat ID'), 'chats', ['Chat ID'], unique=True)
    op.create_index(op.f('ix_chats_Creation Date'), 'chats', ['Creation Date'], unique=False)
    op.create_index(op.f('ix_chats_disabled'), 'chats', ['disabled'], unique=False)
    op.create_table(
        'tasks',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=True),
        sa.Column('description', sa.String(length=128), nullable=True),
        sa.Column('user_id', sa.String(length=20), nullable=True),
        sa.Column('complete', sa.Boolean(), nullable=True),
        sa.Column('Creation Date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(('user_id',), ['users.Phone Number'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_Creation Date'), 'tasks', ['Creation Date'], unique=False)
    op.create_index(op.f('ix_tasks_name'), 'tasks', ['name'], unique=False)
    op.create_table(
        'user_devices',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('User', sa.Text(), nullable=True),
        sa.Column('Platform', sa.String(length=60), nullable=False),
        sa.Column('Role', sa.String(length=60), nullable=True),
        sa.Column('Firebase Token', sa.Text(), nullable=False),
        sa.Column('primary_device', sa.Boolean(), nullable=True),
        sa.Column('Creation Date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(('Role',), ['roles.Name'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(('User',), ['users.User ID'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_devices_Creation Date'), 'user_devices', ['Creation Date'], unique=False)
    op.create_index(op.f('ix_user_devices_primary_device'), 'user_devices', ['primary_device'], unique=False)
    op.create_table(
        'user_roles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Text(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(('role_id',), ['roles.id'], ),
        sa.ForeignKeyConstraint(('user_id',), ['users.User ID'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'messages',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('sender_id', sa.Text(), nullable=True),
        sa.Column('recipient_id', sa.Text(), nullable=True),
        sa.Column('chat_id', sa.Integer(), nullable=True),
        sa.Column('body', sa.Text(), nullable=True),
        sa.Column('starred', sa.Boolean(), nullable=True),
        sa.Column('unread', sa.Boolean(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('type', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(('chat_id',), ['chats.Chat ID'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(('recipient_id',), ['users.User ID'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(('sender_id',), ['users.User ID'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_starred'), 'messages', ['starred'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_messages_type'), 'messages', ['type'], unique=False)
    op.create_index(op.f('ix_messages_unread'), 'messages', ['unread'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_unread'), table_name='messages')
    op.drop_index(op.f('ix_messages_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_messages_starred'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_devices_primary_device'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_Creation Date'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_tasks_name'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_Creation Date'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_chats_disabled'), table_name='chats')
    op.drop_index(op.f('ix_chats_Creation Date'), table_name='chats')
    op.drop_index(op.f('ix_chats_Chat ID'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_users_Gender'), table_name='users')
    op.drop_index(op.f('ix_users_User ID'), table_name='users')
    op.drop_index(op.f('ix_users_Residence'), table_name='users')
    op.drop_index(op.f('ix_users_Phone Number'), table_name='users')
    op.drop_index(op.f('ix_users_Full Name'), table_name='users')
    op.drop_index(op.f('ix_users_Active'), table_name='users')
    op.drop_index(op.f('ix_users_Suspended'), table_name='users')
    op.drop_index(op.f('ix_users_is_confirmed'), table_name='users')
    op.drop_index(op.f('ix_users_Creation Date'), table_name='users')
    op.drop_index(op.f('ix_users_Identification Number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scheduled_tasks_name'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_roles_Name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
