"""Map patients and relatives

Revision ID: e60d1124725d
Revises: c1ae154be95f
Create Date: 2021-03-20 23:00:31.692340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = 'e60d1124725d'
down_revision = 'c1ae154be95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'patient_relatives',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('relative', sa.Text(), nullable=True),
        sa.Column('patient', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True, server_default=func.now()),
        sa.ForeignKeyConstraint(('patient',), ['users.User ID'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(('relative',), ['users.User ID'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_relatives')
    # ### end Alembic commands ###
